"""add push notifications support

Revision ID: 24626d48dd9e
Revises: b1c2d3e4f5g6
Create Date: 2026-01-31 10:36:37.581309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24626d48dd9e'
down_revision: Union[str, Sequence[str], None] = '0a5df8ebbac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_push_subscriptions_usuario_id'), table_name='push_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_push_subscriptions_usuario_id'), 'push_subscriptions', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
